document.write('<li><a href="index.html">Front</a></li>')
document.write('<li><a href="latest.html">Latest</a></li>')
document.write('<li class="dropdown" data-target="dropdown" id="drop1">')
document.write('<a class="dropdown-toggle" data-toggle="dropdown" href="#drop1"> Research <i class="caret"></i> </a>')
document.write('<ul class="dropdown-menu">')
document.write('<li><a href="research.html">Overview</a></li>')
document.write('<li class="divider"></li>')
document.write('<li><a href="xrbs.html">X-Ray Binaries</a></li>')
document.write('<li><a href="blazars.html">Blazars</a></li>')
document.write('<li class="divider"></li>')
document.write('<li><a href="publications.html">Publications</a></li>')
document.write('</ul>')
document.write('</li>')
document.write('<li class="dropdown" data-target="dropdown" id="drop2">')
document.write('<a class="dropdown-toggle" data-toggle="dropdown" href="#drop2"> Code <i class="caret"></i> </a>')
document.write('<ul class="dropdown-menu">')
document.write('<li><a href="http://github.com/omarjamil" target=blank>github</a></li>')
document.write('<li class="divider"></li>')
document.write('<li><a href="http://github.com/omarjamil/SimpleSynch" target=blank>Synchrotron</a></li>')
document.write('<li><a href="http://github.com/omarjamil/SEDfitJS" target=blank>SEDfitJS</a></li>')
document.write('</ul>')
document.write('</li>')
document.write('<li><a href="contact.html">Contact</a></li>')
